SELECT  match_id,
        season,
        start_date,
        venue,
        innings,
        ball,
        batting_team,
        bowling_team,
        striker,
        non_striker,
        bowler,
        runs_off_bat,
        extras,
        wides,
        noballs,
        byes,
        legbyes,
        penalty,
        wicket_type,
        player_dismissed,
        fielder_1,
        fielder_2,
        fielder_3
from read_csv_auto('../raw_data/ball_by_ball.csv')